on: push

jobs:
  linux-x86_64:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'CI skip')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - uses: actions/checkout@v2
        with:
          repository: void-linux/void-packages
          path: void/
      
      - name: Build the package
        timeout-minutes: 30
        env:
          REPO_ADDR: ${{ secrets.REPO_ADDR }}
        run: |
          bash ./run.sh

      - name: Install SSH key of repo
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}

      - name: Deploy packages to repo
        if: success()
        env:
          REPO_SCP_ADDR: ${{ secrets.REPO_SCP_ADDR }}
        run: |
          bash ./deploy.sh
