on: push

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/void-linux/void-glibc-full:latest
      options: --platform linux/amd64 --privileged
      volumes:
        - /dev:/dev
      env:
        ARCH: 'x86_64'
        BOOTSTRAP: 'x86_64'
        TEST: '0'

    if: "!contains(github.event.head_commit.message, 'CI skip')"
    steps:
      - name: Prepare container
        run: |
          # switch to repo-ci mirror
          mkdir -p /etc/xbps.d && cp /usr/share/xbps.d/*-repository-*.conf /etc/xbps.d/
          sed -i 's|repo-default|repo-ci|g' /etc/xbps.d/*-repository-*.conf
          # install dependencies
          xbps-install -Syu xbps && xbps-install -yu && xbps-install -y sudo bash curl git openssh
          # create non-root user
          useradd -G xbuilder -M builder
      
      - name: Clone and checkout
        uses: classabbyamp/treeless-checkout-action@v1

      - name: Fetch void-packages
        run: git clone --depth 1 https://github.com/void-linux/void-packages void/

      - name: Fix ownership
        run: chown -R builder:builder .

      - name: Prepare masterdir
        run: |
          cd void/
          sudo -Eu builder common/travis/set_mirror.sh &&
          sudo -Eu builder common/travis/prepare.sh &&
          common/travis/fetch-xtools.sh

      - name: Build the packages
        timeout-minutes: 30
        env:
          REPO_ADDR: ${{ secrets.REPO_ADDR }}
        run: sudo -Eu builder bash ./run.sh

      - name: Install SSH key of repo
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}

      - name: Deploy packages to repo
        if: success()
        env:
          REPO_SCP_ADDR: ${{ secrets.REPO_SCP_ADDR }}
        run: |
          bash ./deploy.sh
